import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Primitives
        cream: {
          50: "#FAF6F0",
          100: "#F4EDE3",
          200: "#E8DDD0",
        },
        sand: {
          300: "#D4B896",
          400: "#C9A87C",
          500: "#B8925F",
        },
        clay: {
          600: "#8B5E3C",
          700: "#6B4228",
        },
        rust: {
          400: "#C46B42",
          500: "#A8522B",
          600: "#8C3D1A",
        },
        dusk: {
          300: "#9BB5B2",
          400: "#7A9E9A",
          500: "#5E8480",
          600: "#446B67",
        },
        sage: {
          300: "#A3B89A",
          400: "#8AA07E",
          500: "#6E8462",
        },
        ink: {
          800: "#2C2218",
          900: "#1A1410",
        },
        // shadcn required aliases (mapped to Drift tokens)
        border: "var(--border)",
        input: "var(--input)",
        ring: "var(--ring)",
        foreground: "var(--foreground)",
        primary: { DEFAULT: "var(--primary)", foreground: "var(--primary-foreground)" },
        secondary: { DEFAULT: "var(--secondary)", foreground: "var(--secondary-foreground)" },
        muted: { DEFAULT: "var(--muted)", foreground: "var(--muted-foreground)" },
        accent: { DEFAULT: "var(--accent)", foreground: "var(--accent-foreground)" },
        destructive: { DEFAULT: "var(--destructive)" },
        card: { DEFAULT: "var(--card)", foreground: "var(--card-foreground)" },
        popover: { DEFAULT: "var(--popover)", foreground: "var(--popover-foreground)" },
        // Semantic aliases
        background: "#F4EDE3",
        "background-subtle": "#E8DDD0",
        "background-inverse": "#1A1410",
        "surface-card": "#FAF6F0",
        "surface-raised": "#FFFFFF",
        "text-primary": "#1A1410",
        "text-secondary": "#8B5E3C",
        "text-muted": "#B8925F",
        "text-inverse": "#F4EDE3",
        "text-link": "#A8522B",
        "brand-primary": "#A8522B",
        "brand-secondary": "#5E8480",
        "brand-accent": "#C9A87C",
        "status-sold-out-bg": "#E8DDD0",
        "status-sold-out-text": "#B8925F",
        "status-open-bg": "#5E8480",
        "status-open-text": "#FAF6F0",
        "status-closed-bg": "#6B4228",
        "status-closed-text": "#F4EDE3",
        "border-default": "#E8DDD0",
        "border-strong": "#D4B896",
        "border-focus": "#A8522B",
        "admin-nav-bg": "#1A1410",
        "admin-nav-text": "#F4EDE3",
        "admin-nav-active": "#C46B42",
      },
      fontFamily: {
        display: ["Caveat", "cursive"],
        body: ["DM Sans", "sans-serif"],
        sans: ["DM Sans", "sans-serif"],
      },
      fontSize: {
        xs:   ["12px", { lineHeight: "1.5" }],
        sm:   ["14px", { lineHeight: "1.5" }],
        base: ["16px", { lineHeight: "1.6" }],
        lg:   ["18px", { lineHeight: "1.5" }],
        xl:   ["24px", { lineHeight: "1.3" }],
        "2xl": ["32px", { lineHeight: "1.2" }],
        "3xl": ["48px", { lineHeight: "1.1" }],
        "4xl": ["64px", { lineHeight: "1.0" }],
        "5xl": ["80px", { lineHeight: "0.9" }],
      },
      spacing: {
        1: "4px",
        2: "8px",
        3: "12px",
        4: "16px",
        5: "20px",
        6: "24px",
        8: "32px",
        10: "40px",
        12: "48px",
        16: "64px",
        20: "80px",
        24: "96px",
      },
      borderRadius: {
        sm: "4px",
        md: "8px",
        lg: "14px",
        xl: "20px",
        card: "12px",
      },
      boxShadow: {
        sm:   "0 1px 3px rgba(44, 34, 24, 0.10)",
        md:   "0 4px 12px rgba(44, 34, 24, 0.12)",
        lg:   "0 8px 24px rgba(44, 34, 24, 0.16)",
        card: "0 2px 8px rgba(44, 34, 24, 0.10)",
      },
      transitionDuration: {
        fast: "120ms",
        base: "200ms",
        slow: "350ms",
      },
      transitionTimingFunction: {
        default: "cubic-bezier(0.4, 0, 0.2, 1)",
        out: "cubic-bezier(0, 0, 0.2, 1)",
        in: "cubic-bezier(0.4, 0, 1, 1)",
      },
    },
  },
  plugins: [],
};
export default config;
